### ISSUE TITLE
[190216] Daily 만년 Junior들의 이야기

### ISSUE THREAD

**Issue by Wshid** [Wshid/seminar#7]
## Daily 만년 Junior들의 이야기
- **Host** : GDG Campus
- **Date** : 2019년 02월 16일 (토) 오후 01:00 - 오후 06:30
- **Location** : Google For Startup
- [details](https://festa.io/events/192?utm_source=meetup4u.com&utm_medium=direct)

**Comment by banetta** [comment]
# 참가 메일 수신

[본 메일은 GDG Campus Korea의 2월 행사(Daily 만년 Junior들의 이야기 : 델리만주)에 참가신청해주신 분들께 보내는 전체 메일입니다]

안녕하세요. GDG Campus Korea의 2월 행사(Daily 만년 Junior들의 이야기 : 델리만주) 기획팀입니다.

먼저 이번 행사에 관심 가져주시고 신청해주셔서 대단히 감사합니다. 저희 행사 기획팀 모두는 개발자로의 성장을 꿈꾸는 학생과 예비 개발자들을 위한 행사를 준비했습니다. 이와 더불어, 연사자분들께서도 참가자분들에게 유익한 내용을 전달하기 위해 많은 신경을 써주시고 계십니다.

내일이면 여러분들이 기다리시던 행사일입니다. 많은 분들의 관심을 받은 만큼 참가자분들에게 유익한 시간이 되고, 많은 것을 얻어가셨으면 합니다. 원활한 행사 참가를 위해 몇 가지 안내사항들을 미리 알려드립니다.

1. 행사 기본 정보

일시: 2월 16일 13:20 ~ 18:10 (행사장 입장은 13시 정각부터 가능합니다)

장소: Google for Startup Campus - Seoul (서울특별시 강남구 영동대로 417, 오토웨이타워 지하 2층)

세션 소개 : 링크 확인

2. 등록 확인 및 행사장 입장

행사장은 Festa에서 참가권을 구매해주신 분에 한해 입장 가능합니다. 등록 확인은 행사장 입구에서 QR 코드 스캔을 통해서 할 예정입니다 행사장에 들어오시기 전 아래의 링크에 접속(Festa 로그인 필요)해주셔서 QR 코드를 미리 준비해주시기 바랍니다.

QR 코드 링크: https://festa.io/my/tickets/event/192 

연사자 초대권을 통해 참석해주시는 분들은 등록 확인대의 도우미에게 초대해주신 연사자분 성함/본인 성함/본인 연락처를 확인해주시면 입장 가능하신 점 참고해주시기 바랍니다.

3. 행사장 내 와이파이 및 전원 제공 여부

행사장(구글 스타트업 캠퍼스)에서는 방문객을 위한 와이파이를 제공하고 있습니다. 그러나 참가해주시는 모든 분들이 동시에 접속하실 경우 원활한 인터넷 사용이 힘들 수 있습니다.

인터넷 활용이 필요하신 경우, 별도의 연결수단을 준비하시거나, 오프라인 환경에서 사용하실 수 있도록 준비하실 것을 권장합니다.

4. 주차 제공 여부

참가자분들에게는 별도의 주차 제공을 하지 않습니다. 가급적 대중교통을 이용해주시기 바랍니다.

(삼성역 3번 출구로 나오신 후 직진하시면 됩니다. 자세한 위치는 Google Maps 링크를 참고해주시기 바랍니다.)

5. Code of Conduct 준수 요망

GDG Campus Korea는 대학생/학생 개발자 지향 커뮤니티로서, 권리 침해 없는 행사를 위하여 타인에게 불쾌감을 줄 수 있는 발언 및 행동을 금지합니다. 이를 위해 GDG Campus Korea를 비롯한 GDG 커뮤니티의 행사에 참여하시는 모든 분들께 Code of Conduct(행동강령,이하 CoC)을 준수해주실 것을 부탁드리고 있습니다.

CoC의 자세한 내용은 아래 링크를 참고해주시기 바라며, CoC에 위배되는 일을 당하셨거나, 혹은 타인이 이러한 상황에 놓은 것을 목격하셨을 경우 행사장 내 도우미에게, 혹은 gdg-campus@googlegroups.com 에 메일을 보내시어 알려주시기 바랍니다.

CoC 링크 : http://bit.ly/gck-coc-kor 

6. 환불 및 양도 안내

본 행사의 참가권 환불기간은 공식적으로 종료되었으며, 행사 전까지는 참가권 양도만 가능합니다. 양도는 자유로이 가능하며, 양도 받으시는 분에게 참가권 QR코드를 전달해주시면 됩니다.

추가로, GDG Campus Korea의 Facebook 그룹(링크)에서 많은 분들이 양도 받으실 의사를 표현해주셨습니다. 주변에 양도받으실 분이 없을 경우, Facebook 그룹에 양도 의사를 표현해주시어 소중한 참가 기회가 헛되이 되지 않도록 해주실 것을 부탁드립니다.

기타 문의사항은 gdg-campus@googlegroups.com 으로 메일 주시면 답변드리겠습니다.
그럼 내일 행사에서 뵙겠습니다!

감사합니다.

행사 기획팀 일동 드림

**Comment by Wshid** [comment]
- 행사 참여 이후 정리 부탁드립니다 :)
